# /statistics:
is: [requiresSitekey]
description:  "Aggregated statistics.  \n\n (Only requires a sitekey)"

/loans-by-book:
  type: list
  is: [requiresSitekey, paginated, fallible]
  description: |
    List loans per media number during a time period
    (Only requires a sitekey)
  get:
    description:
      Retrieve a list of book loans, ordered by mediaNr (an MTM media specific identifier).
      If there is an error when parsing a marc record then the corresponding bookdetail
      will be empty.
    queryParameters:
      registeredAfter:
        description: Result only includes loans after this date.
        type: string
        required: false
        default: "1900-01-01"
      registeredBefore:
        description: Result only include loans before this date.
        type: string
        required: false
        default: "2099-01-01"
      whereFileFormat:
        description: Filter by format. Possible values are "DAISY_202", "PEF", "TEXTVIEW", "TKN"
        type: string
        required: false
      includePublication:
		description: If notifications regarding authors should be included in response
		type: boolean
    	default: false
    	required: false    
    responses:
      200:
        body:
          application/json:
            schema: statistics-loans.json
            example: !include ../examples/statistics-loans-example.json
